import {v4 as uuid} from 'uuid';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: 'Onion',
    quantity: '1000',
    quantityUnit: 'gram',
    price: 25,
    categoryName: 'Vegetables',
    rating: 4.6,
    image: 'https://farmersfz.com/assets/public/vegimg/BGON8.jpg',
    discount: 10,
  },
  {
    _id: uuid(),
    name: 'Tomato',
    quantityUnit: 'gram',
    quantity: '500',
    price: 16,
    categoryName: 'Vegetables',
    rating: 3.7,
    image: 'https://m.media-amazon.com/images/I/4109t2-iaPL._SX425_.jpg',
  },
  {
    _id: uuid(),
    name: 'Lady Finger',
    quantityUnit: 'gram',
    quantity: '250',
    price: 15,
    categoryName: 'Vegetables',
    rating: 4.7,
    image: 'https://cdn.shopify.com/s/files/1/0244/4961/3905/products/okra.jpg?v=1576806732',
  },
  {
    _id: uuid(),
    name: 'Green Chillies',
    quantityUnit: 'gram',
    quantity: '100',
    price: 15,
    categoryName: 'Vegetables',
    rating: 3.4,
    image:
      'https://cdn.shopify.com/s/files/1/0104/1059/0266/products/Organic-Green-Chilli_large_large_4410288b-ff46-4d7d-8e6b-f9c5775a0d27.jpg?v=1571986449',
  },
  {
    _id: uuid(),
    name: 'Organic Spinach / Palak',
    quantityUnit: 'unit',
    quantity: '1',
    price: 44,
    categoryName: 'Vegetables',
    rating: 2.6,
    description: 'Cleaned and Packed without roots.',
    shelfLife: '3 Days',
    packageWith: 'Roll in a Paper Towel',
    image:
      'https://5.imimg.com/data5/PI/KX/MY-46595757/fresh-spinach-28palak-29-281kg-29-500x500.png',
    discount: 22,
  },

  {
    _id: uuid(),
    name: 'Banana',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 31,
    categoryName: 'Fruits',
    rating: 2.3,
    image:
      'https://media.istockphoto.com/id/173242750/photo/banana-bunch.jpg?s=612x612&w=0&k=20&c=MAc8AXVz5KxwWeEmh75WwH6j_HouRczBFAhulLAtRUU=',
  },
  {
    _id: uuid(),
    name: 'Pomogranates',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 31,
    categoryName: 'Fruits',
    rating: 1.3,
    image:
      'https://images.healthshots.com/healthshots/en/uploads/2021/09/27184641/pomegranate-1600x900.jpg',
  },
  {
    _id: uuid(),
    name: 'Coconut',
    quantityUnit: 'unit',
    quantity: '1',
    price: 47,
    categoryName: 'Fruits',
    rating: 2.6,
    image: 'https://kumaribasket.com/wp-content/uploads/2021/01/Tender-Coconut2.jpg',
  },
  {
    _id: uuid(),
    name: 'Guava',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 64,
    categoryName: 'Fruits',
    rating: 1.6,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAy71WRIKR0JMdAkldQJILTxBl1VaACAAsWw&usqp=CAU',
  },
  {
    _id: uuid(),
    name: 'Kesar Mangoes',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 80,
    categoryName: 'Fruits',
    rating: 4.9,
    image:
      'https://images.ctfassets.net/5djn6ve9uecf/5Avz4k2vOTFbphDuUTcQm7/eee72c2cc2e043b8a430268b46e5c3c2/Kesar_shutterstock_1708900531_copy.jpg',
  },

  // all bakery products are in gram
  {
    _id: uuid(),
    name: 'Bread - Brown',
    quantityUnit: 'gram',
    quantity: '400',
    price: 55,
    categoryName: 'Bakery and Biscuits',
    rating: 1.5,
    image:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Fresh_made_bread_05.jpg/1200px-Fresh_made_bread_05.jpg',
  },
  {
    _id: uuid(),
    name: 'White Sandwich Bread',
    quantityUnit: 'gram',
    quantity: '400',
    price: 50,
    categoryName: 'Bakery and Biscuits',
    rating: 3.2,
    image: 'https://www.goldmedalbakery.com/content/uploads/2019/12/Sandwich-White.jpg',
  },
  {
    _id: uuid(),
    name: 'Crozzo Assorted Croissants Pack Of 2',
    quantityUnit: 'unit',
    quantity: '1',
    price: 229,
    categoryName: 'Bakery and Biscuits',
    rating: 2.8,
    image:
      'https://cdn.shopify.com/s/files/1/0511/2158/6327/products/AssortedCroissantBox1_1024x.jpg?v=1644310793',
  },
  {
    _id: uuid(),
    name: 'Multigrain Sandwich Bread',
    quantityUnit: 'gram',
    quantity: '150',
    price: 70,
    categoryName: 'Bakery and Biscuits',
    rating: 3.7,
    image:
      'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image/public/recipe_legacy/9027-3-large.jpg?itok=cYIGvAGS',
  },
  {
    _id: uuid(),
    name: 'Brownie Cottage Pure Hot Fudge',
    quantityUnit: 'unit',
    quantity: '1',
    price: 230,
    categoryName: 'Bakery and Biscuits',
    rating: 2.5,
    image:
      'https://d1z88p83zuviay.cloudfront.net/ProductVariantImages/3c95f219-2ccc-47fa-817f-bdb948cb574f.jpg',
  },

  {
    _id: uuid(),
    name: 'Almonds',
    quantityUnit: 'gram',
    quantity: '200',
    price: 181,
    categoryName: 'Dry-Fruits',
    rating: 3.5,
    image: 'https://m.media-amazon.com/images/I/51ODBfoqozL.jpg',
  },
  {
    _id: uuid(),
    name: 'Cashews',
    quantityUnit: 'gram',
    quantity: '200',
    price: 210,
    categoryName: 'Dry-Fruits',
    rating: 2.8,
    image: 'https://dspices.in/image/cache/catalog/products/cashew/cw_1-800x800.jpg',
  },
  {
    _id: uuid(),
    name: 'Raisins',
    quantityUnit: 'gram',
    quantity: '200',
    price: 62,
    categoryName: 'Dry-Fruits',
    rating: 2.5,
    image: 'https://www.dryfruitshome.com/wp-content/uploads/2020/10/munakka.jpg',
  },
  {
    _id: uuid(),
    name: 'Salted Pistachios',
    quantityUnit: 'gram',
    quantity: '200',
    price: 272,
    categoryName: 'Dry-Fruits',
    rating: 2.8,
    image: 'https://indiacuisine.net/cdn/shop/products/PISTA.jpg?v=1615638822',
  },
  {
    _id: uuid(),
    name: 'Mix Berries',
    quantityUnit: 'gram',
    quantity: '200',
    price: 365,
    categoryName: 'Dry-Fruits',
    rating: 1.3,
    image: 'https://m.media-amazon.com/images/I/51h1HtbZYWL.jpg',
  },

  {
    _id: uuid(),
    name: 'Full Cream Fresh Milk ',
    quantityUnit: 'ml',
    quantity: '500',
    price: 33,
    categoryName: 'Dairy',
    rating: 1.9,
    image: 'https://foodsguy.com/wp-content/uploads/2022/04/Milk.jpg',
  },
  {
    _id: uuid(),
    name: 'Cheese Slices',
    quantityUnit: 'gram',
    quantity: '200',
    price: 138,
    categoryName: 'Dairy',
    rating: 2.6,
    image: 'https://gourmet-foods.in/wp-content/uploads/2021/07/sliced-cheese-500x500-1.jpg',
  },
  {
    _id: uuid(),
    name: 'Fresh Malai Paneer',
    quantityUnit: 'gram',
    quantity: '200',
    price: 91,
    categoryName: 'Dairy',
    rating: 3.6,
    image:
      'https://5.imimg.com/data5/ANDROID/Default/2022/10/GI/MP/QC/100746515/product-jpeg-500x500.jpg',
  },
  {
    _id: uuid(),
    name: 'Salted Butter',
    quantityUnit: 'gram',
    quantity: '200',
    price: 114,
    categoryName: 'Dairy',
    rating: 4.3,
    image:
      'https://www.southernliving.com/thmb/S3jnGzbVG4VUSMFqU-Ohjw3pdFE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/butter_cutting_board-179875636-2000-14b4ec54a0a64d2f8c884822acb68415.jpg',
  },
  {
    _id: uuid(),
    name: 'Spiced Buttermilk',
    quantityUnit: 'ml',
    quantity: '500',
    price: 22,
    categoryName: 'Dairy',
    rating: 1.3,
    image:
      'https://static.wixstatic.com/media/cdf1d3_a7c86a153904481faa5bde2eb5b1f88b~mv2.jpg/v1/fill/w_601,h_600,al_c,q_85/cdf1d3_a7c86a153904481faa5bde2eb5b1f88b~mv2.jpg',
  },
  {
    _id: uuid(),
    name: 'Healthy Daily Eggs',
    quantityUnit: 'pcs',
    quantity: '6',
    price: 90,
    categoryName: 'Eggs-Meat-Fish',
    rating: 2.3,
    image: 'https://www.netojin.com/wp-content/uploads/2022/02/egg.jpg',
  },
  {
    _id: uuid(),
    name: 'Healthy Brown Eggs',
    quantityUnit: 'pcs',
    quantity: '6',
    price: 90,
    categoryName: 'Eggs-Meat-Fish',
    rating: 2.4,
    image:
      'https://cdn3.mydukaan.io/app/image/1000x1000/?url=https://projecteagle.s3.ap-south-1.amazonaws.com/images/9fe6f688-d136-4b98-a531-7a1d5084fffd.jpg',
  },
  {
    _id: uuid(),
    name: 'Frozon Shrimp',
    quantityUnit: 'gram',
    quantity: '250',
    price: 1295,
    categoryName: 'Eggs-Meat-Fish',
    rating: 2.4,
    image: '',
  },
];
