import {v4 as uuid} from 'uuid';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: 'Onion',
    quantity: '1000',
    quantityUnit: 'gram',
    price: 25,
    categoryName: 'Vegetables',
    rating: 4.6,
  },
  {
    _id: uuid(),
    name: 'Tomato',
    quantityUnit: 'gram',
    quantity: '500',
    price: 16,
    categoryName: 'Vegetables',
    rating: 3.7,
  },
  {
    _id: uuid(),
    name: 'Lady Finger',
    quantityUnit: 'gram',
    quantity: '250',
    price: 15,
    categoryName: 'Vegetables',
    rating: 4.7,
  },
  {
    _id: uuid(),
    name: 'Green Chillies',
    quantityUnit: 'gram',
    quantity: '100',
    price: 15,
    categoryName: 'Vegetables',
    rating: 3.4,
  },
  {
    _id: uuid(),
    name: 'Organic Spinach / Palak',
    quantityUnit: 'unit',
    quantity: '1',
    price: 44,
    categoryName: 'Vegetables',
    rating: 2.6,
  },

  {
    _id: uuid(),
    name: 'Banana',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 31,
    categoryName: 'Fruits',
    rating: 2.3,
  },
  {
    _id: uuid(),
    name: 'Pomogranates',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 31,
    categoryName: 'Fruits',
    rating: 3.3,
  },
  {
    _id: uuid(),
    name: 'Coconut',
    quantityUnit: 'unit',
    quantity: '1',
    price: 47,
    categoryName: 'Fruits',
    rating: 3.6,
  },
  {
    _id: uuid(),
    name: 'Guava',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 64,
    categoryName: 'Fruits',
  },
  {
    _id: uuid(),
    name: 'Kesar Mangoes',
    quantityUnit: 'gram',
    quantity: '1000',
    price: 80,
    categoryName: 'Fruits',
  },

  // all bakery products are in gram
  {
    _id: uuid(),
    name: 'Bread - Brown',
    quantityUnit: 'gram',
    quantity: '400',
    price: 55,
    categoryName: 'Bakery and Biscuits',
    rating: 1.5,
  },
  {
    _id: uuid(),
    name: 'White Sandwich Bread',
    quantityUnit: 'gram',
    quantity: '400',
    price: 50,
    categoryName: 'Bakery and Biscuits',
    rating: 3.5,
  },
  {
    _id: uuid(),
    name: 'Crozzo Assorted Croissants Pack Of 2',
    quantityUnit: 'unit',
    quantity: '1',
    price: 229,
    categoryName: 'Bakery and Biscuits',
    rating: 4.8,
  },
  {
    _id: uuid(),
    name: 'Multigrain Sandwich Bread',
    quantityUnit: 'gram',
    quantity: '150',
    price: 70,
    categoryName: 'Bakery and Biscuits',
  },
  {
    _id: uuid(),
    name: 'Brownie Cottage Pure Hot Fudge',
    quantityUnit: 'unit',
    quantity: '1',
    price: 230,
    categoryName: 'Bakery and Biscuits',
  },

  {
    _id: uuid(),
    name: 'Almonds',
    quantityUnit: 'gram',
    quantity: '200',
    price: 181,
    categoryName: 'Dry-Fruits',
  },
  {
    _id: uuid(),
    name: 'Cashews',
    quantityUnit: 'gram',
    quantity: '200',
    price: 210,
    categoryName: 'Dry-Fruits',
  },
  {
    _id: uuid(),
    name: 'Raisins',
    quantityUnit: 'gram',
    quantity: '200',
    price: 62,
    categoryName: 'Dry-Fruits',
    rating: 2.5,
  },
  {
    _id: uuid(),
    name: 'Salted Pistachios',
    quantityUnit: 'gram',
    quantity: '200',
    price: 272,
    categoryName: 'Dry-Fruits',
    rating: 2.8,
  },
  {
    _id: uuid(),
    name: 'Mix Berries',
    quantityUnit: 'gram',
    quantity: '200',
    price: 365,
    categoryName: 'Dry-Fruits',
    rating: 1.3,
  },

  {
    _id: uuid(),
    name: 'Full Cream Fresh Milk ',
    quantityUnit: 'ml',
    quantity: '500',
    price: 33,
    categoryName: 'Dairy',
  },
  {
    _id: uuid(),
    name: 'Cheese Slices',
    quantityUnit: 'gram',
    quantity: '200',
    price: 138,
    categoryName: 'Dairy',
    rating: 2.6,
  },
  {
    _id: uuid(),
    name: 'Fresh Malai Paneer',
    quantityUnit: 'gram',
    quantity: '200',
    price: 91,
    categoryName: 'Dairy',
  },
  {
    _id: uuid(),
    name: 'Salted Butter',
    quantityUnit: 'gram',
    quantity: '200',
    price: 114,
    categoryName: 'Dairy',
  },
  {
    _id: uuid(),
    name: 'Spiced Buttermilk',
    quantityUnit: 'ml',
    quantity: '500',
    price: 22,
    categoryName: 'Dairy',
  },
];
